fix an autobug
java.lang.RuntimeException: Unable to create service com.geeksville.andropilot.service.AndropilotService: java.util.NoSuchElementException: None.get
at android.app.ActivityThread.handleCreateService(ActivityThread.java:2586)
at android.app.ActivityThread.access$1700(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1358)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5216)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.util.NoSuchElementException: None.get
at scala.None$.get(Option.scala:313)
at scala.None$.get(Option.scala:311)
at com.geeksville.andropilot.service.USBAndroidSerial.open(AndroidSerial.scala:148)
at com.geeksville.andropilot.service.USBAndroidSerial.<init>(AndroidSerial.scala:38)
at com.geeksville.andropilot.service.MavlinkAndroid$.create(MavlinkAndroid.scala:27)
at com.geeksville.andropilot.service.AndropilotService$$anonfun$serialAttached$2.apply(AndropilotService.scala:299)
at com.geeksville.andropilot.service.AndropilotService.serialAttached(AndropilotService.scala:289)
at com.geeksville.andropilot.service.AndropilotService.onCreate(AndropilotService.scala:170)
at android.app.ActivityThread.handleCreateService(ActivityThread.java:2576)
... 10 more
java.util.NoSuchElementException: None.get
at scala.None$.get(Option.scala:313)
at scala.None$.get(Option.scala:311)
at com.geeksville.andropilot.service.USBAndroidSerial.open(AndroidSerial.scala:148)
at com.geeksville.andropilot.service.USBAndroidSerial.<init>(AndroidSerial.scala:38)
at com.geeksville.andropilot.service.MavlinkAndroid$.create(MavlinkAndroid.scala:27)
at com.geeksville.andropilot.service.AndropilotService$$anonfun$serialAttached$2.apply(AndropilotService.scala:299)
at com.geeksville.andropilot.service.AndropilotService.serialAttached(AndropilotService.scala:289)
at com.geeksville.andropilot.service.AndropilotService.onCreate(AndropilotService.scala:170)
at android.app.ActivityThread.handleCreateService(ActivityThread.java:2576)
at android.app.ActivityThread.access$1700(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1358)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5216)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
at dalvik.system.NativeStart.main(Native Method)