'fix' an autobug, if multiple serial devices attached, just use the first one
java.lang.RuntimeException: Unable to create service com.geeksville.andropilot.service.AndropilotService: java.io.IOException: FIXME, multiple devices attached - not yet supported
at android.app.ActivityThread.handleCreateService(ActivityThread.java:2539)
at android.app.ActivityThread.access$1600(ActivityThread.java:141)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5041)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.io.IOException: FIXME, multiple devices attached - not yet supported
at com.geeksville.andropilot.service.AndroidSerial$.getDevice(AndroidSerial.scala:232)
at com.geeksville.andropilot.service.AndropilotService.serialAttached(AndropilotService.scala:252)
at com.geeksville.andropilot.service.AndropilotService.onCreate(AndropilotService.scala:161)
at android.app.ActivityThread.handleCreateService(ActivityThread.java:2529)
... 10 more
java.io.IOException: FIXME, multiple devices attached - not yet supported
at com.geeksville.andropilot.service.AndroidSerial$.getDevice(AndroidSerial.scala:232)
at com.geeksville.andropilot.service.AndropilotService.serialAttached(AndropilotService.scala:252)
at com.geeksville.andropilot.service.AndropilotService.onCreate(AndropilotService.scala:161)
at android.app.ActivityThread.handleCreateService(ActivityThread.java:2529)
at android.app.ActivityThread.access$1600(ActivityThread.java:141)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5041)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
at dalvik.system.NativeStart.main(Native Method)