fix an autobug reported on some chinese tablet - not allowed to open udp
java.net.BindException: bind failed: EACCES (Permission denied)
at libcore.io.IoBridge.bind(IoBridge.java:89)
at java.net.PlainDatagramSocketImpl.bind(PlainDatagramSocketImpl.java:68)
at java.net.DatagramSocket.createSocket(DatagramSocket.java:133)
at java.net.DatagramSocket.<init>(DatagramSocket.java:78)
at com.geeksville.mavlink.MavlinkUDP.socket$lzycompute(MavlinkUDP.scala:29)
at com.geeksville.mavlink.MavlinkUDP.socket(MavlinkUDP.scala:29)
at com.geeksville.mavlink.MavlinkUDP.receivePacket(MavlinkUDP.scala:68)
at com.geeksville.mavlink.MavlinkUDP.com$geeksville$mavlink$MavlinkUDP$$worker(MavlinkUDP.scala:94)
at com.geeksville.mavlink.MavlinkUDP$$anonfun$1.apply(MavlinkUDP.scala:31)
at com.geeksville.mavlink.MavlinkUDP$$anonfun$1.apply(MavlinkUDP.scala:31)
at com.geeksville.util.ThreadTools$$anon$1.run(ThreadTools.scala:11)
at java.lang.Thread.run(Thread.java:856)
Caused by: libcore.io.ErrnoException: bind failed: EACCES (Permission denied)
at libcore.io.Posix.bind(Native Method)
at libcore.io.ForwardingOs.bind(ForwardingOs.java:39)
at libcore.io.IoBridge.bind(IoBridge.java:87)
... 11 more
libcore.io.ErrnoException: bind failed: EACCES (Permission denied)
at libcore.io.Posix.bind(Native Method)
at libcore.io.ForwardingOs.bind(ForwardingOs.java:39)
at libcore.io.IoBridge.bind(IoBridge.java:87)
at java.net.PlainDatagramSocketImpl.bind(PlainDatagramSocketImpl.java:68)
at java.net.DatagramSocket.createSocket(DatagramSocket.java:133)
at java.net.DatagramSocket.<init>(DatagramSocket.java:78)
at com.geeksville.mavlink.MavlinkUDP.socket$lzycompute(MavlinkUDP.scala:29)
at com.geeksville.mavlink.MavlinkUDP.socket(MavlinkUDP.scala:29)
at com.geeksville.mavlink.MavlinkUDP.receivePacket(MavlinkUDP.scala:68)
at com.geeksville.mavlink.MavlinkUDP.com$geeksville$mavlink$MavlinkUDP$$worker(MavlinkUDP.scala:94)
at com.geeksville.mavlink.MavlinkUDP$$anonfun$1.apply(MavlinkUDP.scala:31)
at com.geeksville.mavlink.MavlinkUDP$$anonfun$1.apply(MavlinkUDP.scala:31)
at com.geeksville.util.ThreadTools$$anon$1.run(ThreadTools.scala:11)
at java.lan