fix auto bug report when failing to connect to APM for the first time
java.lang.RuntimeException: Unable to create service com.geeksville.andropilot.AndropilotService: java.io.IOException: Could not claim control interface.
at android.app.ActivityThread.handleCreateService(ActivityThread.java:2664)
at android.app.ActivityThread.access$1600(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1327)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5200)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.io.IOException: Could not claim control interface.
at com.hoho.android.usbserial.driver.CdcAcmSerialDriver.open(CdcAcmSerialDriver.java:62)
at com.geeksville.andropilot.AndroidSerial.open(AndroidSerial.scala:185)
at com.geeksville.andropilot.AndroidSerial.<init>(AndroidSerial.scala:64)
at com.geeksville.andropilot.MavlinkAndroid$.create(MavlinkAndroid.scala:11)
at com.geeksville.andropilot.AndropilotService$$anonfun$serialAttached$2.apply(AndropilotService.scala:219)
at com.geeksville.andropilot.AndropilotService.serialAttached(AndropilotService.scala:209)
at com.geeksville.andropilot.AndropilotService.onCreate(AndropilotService.scala:156)
at android.app.ActivityThread.handleCreateService(ActivityThread.java:2654)
... 10 more
java.io.IOException: Could not claim control interface.
at com.hoho.android.usbserial.driver.CdcAcmSerialDriver.open(CdcAcmSerialDriver.java:62)
at com.geeksville.andropilot.AndroidSerial.open(AndroidSerial.scala:185)
at com.geeksville.andropilot.AndroidSerial.<init>(AndroidSerial.scala:64)
at com.geeksville.andropilot.MavlinkAndroid$.create(MavlinkAndroid.scala:11)
at com.geeksville.andropilot.AndropilotService$$anonfun$serialAttached$2.apply(AndropilotService.scala:219)
at com.geeksville.andropilot.AndropilotService.serialAttached(AndropilotService.scala:209)
at com.geeksville.andropilot.AndropilotService.onCreate(AndropilotService.scala:156)
at android.app.ActivityThread.handleCreateService(ActivityThread.java:2654)
at android.app.ActivityThread.access$1600(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1327)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5200)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
at dalvik.system.NativeStart.main(Native Method